'use client';

import React, { useState } from 'react';
import { useAppState } from '@/lib/useAppState';
import { Wrench, CheckCircle2, Clock, AlertTriangle, ShieldCheck, Filter } from 'lucide-react';

export default function MaintenanceAdvisoryPage() {
  const state = useAppState();
  const [filterPriority, setFilterPriority] = useState<string>('ALL');

  const advisories = state.maintenanceAdvisories.filter((m) => {
    if (filterPriority === 'ALL') return true;
    return m.priority === filterPriority;
  });

  const getPriorityBadge = (p: string) => {
    switch (p) {
      case 'CRITICAL':
        return 'bg-rose-500 text-white font-black';
      case 'HIGH':
        return 'bg-rose-500/20 text-rose-300 border border-rose-500/40 font-bold';
      case 'MEDIUM':
        return 'bg-amber-500/20 text-amber-300 border border-amber-500/40 font-bold';
      default:
        return 'bg-slate-800 text-slate-300 border border-slate-700';
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="p-4 rounded-xl bg-[#0c1220] border border-slate-800 flex flex-wrap items-center justify-between gap-4">
        <div>
          <h1 className="text-lg font-bold text-white tracking-wide flex items-center gap-2">
            <Wrench className="w-5 h-5 text-amber-400" />
            <span>INTELLIGENT PREDICTIVE MAINTENANCE ADVISORY QUEUE</span>
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Condition-based maintenance directives generated by AI diagnostics, physical margin limits, and operating hour thresholds.
          </p>
        </div>

        {/* Priority Filter */}
        <div className="flex items-center gap-2 text-xs font-mono">
          <Filter className="w-3.5 h-3.5 text-slate-400" />
          <span className="text-slate-400">PRIORITY:</span>
          {['ALL', 'CRITICAL', 'HIGH', 'MEDIUM', 'LOW'].map((p) => (
            <button
              key={p}
              onClick={() => setFilterPriority(p)}
              className={`px-2 py-1 rounded text-[11px] font-mono transition ${
                filterPriority === p
                  ? 'bg-cyan-500 text-black font-bold'
                  : 'bg-slate-900 border border-slate-800 text-slate-400 hover:text-white'
              }`}
            >
              {p}
            </button>
          ))}
        </div>
      </div>

      {/* Advisory Queue List */}
      <div className="space-y-4">
        {advisories.length === 0 ? (
          <div className="aerospace-panel p-8 text-center space-y-2">
            <ShieldCheck className="w-8 h-8 text-emerald-400 mx-auto" />
            <h3 className="text-sm font-bold text-white">NO PENDING MAINTENANCE DIRECTIVES</h3>
            <p className="text-xs text-slate-400">All propulsion components conform to scheduled maintenance intervals.</p>
          </div>
        ) : (
          advisories.map((adv) => (
            <div
              key={adv.id}
              className={`aerospace-panel p-5 space-y-3 transition border-l-4 ${
                adv.priority === 'CRITICAL'
                  ? 'border-l-rose-500 border-slate-800 bg-rose-950/10'
                  : adv.priority === 'HIGH'
                  ? 'border-l-amber-500 border-slate-800'
                  : 'border-l-cyan-500 border-slate-800'
              }`}
            >
              <div className="flex flex-wrap items-start justify-between gap-3">
                <div>
                  <div className="flex items-center gap-2">
                    <span className={`px-2 py-0.5 rounded text-[10px] font-mono ${getPriorityBadge(adv.priority)}`}>
                      {adv.priority} PRIORITY
                    </span>
                    <span className="text-[10px] font-mono text-slate-400">
                      ID: {adv.id} | Subsystem: {adv.subsystem}
                    </span>
                  </div>
                  <h3 className="text-base font-bold text-white mt-1">{adv.issue}</h3>
                </div>

                <div className="flex items-center gap-2 text-xs font-mono">
                  <div className="flex items-center gap-1 text-slate-400">
                    <Clock className="w-3.5 h-3.5" />
                    <span>Urgency: ~{adv.estimatedUrgencyHours} flight hrs</span>
                  </div>
                  <span className="px-2 py-0.5 rounded bg-slate-900 text-cyan-300 border border-slate-700 font-bold">
                    STATUS: {adv.status}
                  </span>
                </div>
              </div>

              {/* Rationale & Inspection Guidance */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
                <div className="bg-slate-900/60 p-3 rounded-lg border border-slate-800 space-y-1">
                  <span className="text-[10px] font-mono text-slate-400 uppercase font-bold">Diagnostic Reason</span>
                  <p className="text-slate-300 leading-relaxed">{adv.reason}</p>
                </div>

                <div className="bg-cyan-950/20 p-3 rounded-lg border border-cyan-500/30 space-y-1">
                  <span className="text-[10px] font-mono text-cyan-400 uppercase font-bold">Actionable Inspection Guide</span>
                  <p className="text-slate-200 leading-relaxed">{adv.suggestedInspection}</p>
                </div>
              </div>

              {/* Supporting Evidence */}
              <div className="flex flex-wrap items-center gap-2 text-xs font-mono pt-1 text-slate-400">
                <span className="text-[10px] uppercase font-bold text-slate-500">Supporting Evidence:</span>
                {adv.supportingEvidence.map((ev, i) => (
                  <span key={i} className="px-2 py-0.5 rounded bg-slate-900 text-slate-300 border border-slate-800">
                    {ev}
                  </span>
                ))}
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}
